/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package praefectus.view;

import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JTable;

/**
 *
 * @author soares
 */
public class SprintView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProjetoView
     */
    public SprintView() {
        initComponents();
    }

    public JButton getjButtonNovaSprint() {
        return jButtonNovaSprint;
    }

    public JButton getjButtonSalvar() {
        return jButtonSalvar;
    }

    public JButton getjButtonSprintBacklog() {
        return jButtonSprintBacklog;
    }

    public JFormattedTextField getjFormattedTextFieldFim() {
        return jFormattedTextFieldFim;
    }

    public JFormattedTextField getjFormattedTextFieldInicio() {
        return jFormattedTextFieldInicio;
    }

    public JTable getjTableSprintBacklog() {
        return jTableSprintBacklog;
    }

    public JTable getjTableSprints() {
        return jTableSprints;
    }

    public JButton getjButtonChart() {
        return jButtonChart;
    }

    public JButton getjButtonReview() {
        return jButtonReview;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSprints = new javax.swing.JPanel();
        jScrollPaneSprints = new javax.swing.JScrollPane();
        jTableSprints = new javax.swing.JTable();
        jButtonNovaSprint = new javax.swing.JButton();
        jButtonSprintBacklog = new javax.swing.JButton();
        jButtonChart = new javax.swing.JButton();
        jButtonReview = new javax.swing.JButton();
        jPanelProjeto = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jFormattedTextFieldInicio = new javax.swing.JFormattedTextField();
        jFormattedTextFieldFim = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanelSprintBacklog = new javax.swing.JPanel();
        jScrollPaneSprintBacklog = new javax.swing.JScrollPane();
        jTableSprintBacklog = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Sprints");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Sprints"); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        jPanelSprints.setBorder(javax.swing.BorderFactory.createTitledBorder("Sprints"));

        jScrollPaneSprints.setAutoscrolls(true);

        jTableSprints.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Inicio", "Fim"
            }
        ));
        jTableSprints.setRequestFocusEnabled(false);
        jTableSprints.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPaneSprints.setViewportView(jTableSprints);

        jButtonNovaSprint.setText("+");

        jButtonSprintBacklog.setText("Sprint Backlog");

        jButtonChart.setText("Burn Down Chart");

        jButtonReview.setText("Sprint Review");

        javax.swing.GroupLayout jPanelSprintsLayout = new javax.swing.GroupLayout(jPanelSprints);
        jPanelSprints.setLayout(jPanelSprintsLayout);
        jPanelSprintsLayout.setHorizontalGroup(
            jPanelSprintsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSprintsLayout.createSequentialGroup()
                .addComponent(jButtonChart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonReview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSprintBacklog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jButtonNovaSprint))
            .addGroup(jPanelSprintsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPaneSprints, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        jPanelSprintsLayout.setVerticalGroup(
            jPanelSprintsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSprintsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelSprintsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovaSprint)
                    .addComponent(jButtonSprintBacklog)
                    .addComponent(jButtonChart)
                    .addComponent(jButtonReview)))
            .addGroup(jPanelSprintsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelSprintsLayout.createSequentialGroup()
                    .addComponent(jScrollPaneSprints)
                    .addGap(28, 28, 28)))
        );

        jPanelProjeto.setBorder(javax.swing.BorderFactory.createTitledBorder("Sprint"));

        jLabel3.setText("Data Inicio:");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setActionCommand("");

        jFormattedTextFieldInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFormattedTextFieldInicio.setToolTipText("Data de início");

        jFormattedTextFieldFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFormattedTextFieldFim.setToolTipText("Data término");

        jLabel6.setText("Data Fim:");

        jPanelSprintBacklog.setBorder(javax.swing.BorderFactory.createTitledBorder("Sprint Backlog"));

        jScrollPaneSprintBacklog.setAutoscrolls(true);

        jTableSprintBacklog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prioridade", "Estimativa", "Status", "Estória"
            }
        ));
        jTableSprintBacklog.setRequestFocusEnabled(false);
        jTableSprintBacklog.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPaneSprintBacklog.setViewportView(jTableSprintBacklog);

        javax.swing.GroupLayout jPanelSprintBacklogLayout = new javax.swing.GroupLayout(jPanelSprintBacklog);
        jPanelSprintBacklog.setLayout(jPanelSprintBacklogLayout);
        jPanelSprintBacklogLayout.setHorizontalGroup(
            jPanelSprintBacklogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneSprintBacklog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );
        jPanelSprintBacklogLayout.setVerticalGroup(
            jPanelSprintBacklogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneSprintBacklog, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelProjetoLayout = new javax.swing.GroupLayout(jPanelProjeto);
        jPanelProjeto.setLayout(jPanelProjetoLayout);
        jPanelProjetoLayout.setHorizontalGroup(
            jPanelProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProjetoLayout.createSequentialGroup()
                        .addGroup(jPanelProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelProjetoLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 129, Short.MAX_VALUE))
                            .addComponent(jFormattedTextFieldFim, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addComponent(jPanelSprintBacklog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProjetoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSalvar)))
                .addContainerGap())
        );
        jPanelProjetoLayout.setVerticalGroup(
            jPanelProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjetoLayout.createSequentialGroup()
                .addGroup(jPanelProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(1, 1, 1)
                .addGroup(jPanelProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSprintBacklog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelSprints, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSprints, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-959)/2, (screenSize.height-435)/2, 959, 435);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChart;
    private javax.swing.JButton jButtonNovaSprint;
    private javax.swing.JButton jButtonReview;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonSprintBacklog;
    private javax.swing.JFormattedTextField jFormattedTextFieldFim;
    private javax.swing.JFormattedTextField jFormattedTextFieldInicio;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelProjeto;
    private javax.swing.JPanel jPanelSprintBacklog;
    private javax.swing.JPanel jPanelSprints;
    private javax.swing.JScrollPane jScrollPaneSprintBacklog;
    private javax.swing.JScrollPane jScrollPaneSprints;
    private javax.swing.JTable jTableSprintBacklog;
    private javax.swing.JTable jTableSprints;
    // End of variables declaration//GEN-END:variables
}
